# manifests/01-configmap.yaml
# Crea un ConfigMap con par치metros de configuraci칩n para la base de datos del backend
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config  # Nombre del ConfigMap
  labels:
    app: financial-backend  # Etiqueta que identifica la aplicaci칩n asociada
data:
  DB_HOST: mysql-deployment  # Nombre del servicio/deployment de la base de datos
  DB_PORT: "3306"            # Puerto de conexi칩n de MySQL
  DB_NAME: finanzas          # Nombre de la base de datos
