# manifests/02-secret.yaml
# Crea un secreto que almacena credenciales sensibles para la base de datos
apiVersion: v1
kind: Secret
metadata:
  name: db-secret  # Nombre del secreto
  labels:
    app: financial-db  # Etiqueta para identificar a qué app pertenece
type: Opaque  # Tipo estándar de secreto (codificado en base64)
stringData:
  username: financiero        # Usuario de la base de datos
  password: supersecreto123   # Contraseña de la base de datos